### ISSUE TITLE
De-alias type aliases when it resolves into a function

### ISSUE THREAD

**Issue by tim2CF** [wende/elchemy#245]
I'm trying to use `matthewsj/elm-ordering` as dependency. Elixir source code is generated OK. But Elixir compiler is not happy with generated source code. Elixir version 1.5.3. Example

## Example:
```elm
fromLessThan : (a -> a -> Bool) -> Ordering a
fromLessThan lt x y =
    if lt x y then
        LT
    else if lt y x then
        GT
    else
        EQ
```
->
```elixir
  @spec from_less_than((any -> (any -> boolean))) :: ordering(any)
  curry from_less_than/1
  def from_less_than(lt, x, y) do
    cond do
      lt.(x).(y) -> :lt
      lt.(y).(x) -> :gt
      true -> :eq
    end
  end
```
## Compiler
```
== Compilation error in file elm-deps/tim2CF/elm-ordering/1.1.1/src/Ordering.elchemy.ex ==
** (CompileError) elm-deps/tim2CF/elm-ordering/1.1.1/src/Ordering.elchemy.ex:87: spec for undefined function from_less_than/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by wende** [comment]
Oh wow. I've never seen a type alias to be used that way
So the Ordering resolves from
```
fromLessThan : (a -> a -> Bool) -> Ordering a
```
to
```
fromLessThan : (a -> a -> Bool) -> (a -> a -> Order a)
```.

It probably was working before, but got bugged after aliases were made resolving to argumented types in #31

**Comment by wende** [comment]
Right now there is an exception of resolving type aliases when applied to Structs polymorphism (because Elixir has none).
It should be enough to just add functions as an another exception

**Comment by tim2CF** [comment]
Thanks!
So to make it work right now, I should fork this library and replace 
```
Ordering a
```
type with
```
a -> a -> Order
```
i.e. to not use this type alias?

Library is pretty small so it can be done easily

**Comment by wende** [comment]
@tim2CF Yes. You could do that. But the library still uses valid code, so it definitely should be working. It seems like a minor change. I should be able to do that today. I'll keep you updated

**Comment by tim2CF** [comment]
Ok!

**Comment by tim2CF** [comment]
Hello @wende 
It's different issue, but can be reproduced with the same library `matthewsj/elm-ordering@1.1.0`

Elm code

```elm
explicit : List a -> Ordering a
explicit items x y =
    let
        scanForEither items =
            case items of
                z :: zs ->
                    if z == x then
                        scanForY zs
                    else if z == y then
                        scanForX zs
                    else
                        scanForEither zs

                [] ->
                    EQ

        scanForX items =
            case items of
                z :: zs ->
                    if z == x then
                        GT
                    else
                        scanForX zs

                [] ->
                    LT

        scanForY items =
            case items of
                z :: zs ->
                    if z == y then
                        LT
                    else
                        scanForY zs

                [] ->
                    GT
    in
        if x == y then
            EQ
        else
            scanForEither items
```

compiles to Elixir code

```elixir
  @spec explicit(list(any), any, any) :: Elchemy.XBasics.order
  curry explicit/3
  def explicit(items, x, y) do
    scan_for_either = rec scan_for_either, fn items -> case items do
      [z | zs] ->
        cond do
          (z == x) -> scan_for_y().(zs)
          (z == y) -> scan_for_x().(zs)
          true -> scan_for_either.(zs)
        end
      [] ->
        :eq
    end end
    scan_for_x = rec scan_for_x, fn items -> case items do
      [z | zs] ->
        if (z == x) do :gt else scan_for_x.(zs) end
      [] ->
        :lt
    end end
    scan_for_y = rec scan_for_y, fn items -> case items do
      [z | zs] ->
        if (z == y) do :lt else scan_for_y.(zs) end
      [] ->
        :gt
    end end
    if (x == y) do :eq else scan_for_either.(items) end
  end
```

and Elixir compiler says

```
== Compilation error in file src/Ordering.elchemy.ex ==
** (CompileError) src/Ordering.elchemy.ex:129: undefined function scan_for_y/0
```
