### ISSUE TITLE
Elchemy-live doesn't work

### ISSUE THREAD

**Issue by azazel75** [wende/elchemy#370]
Visiting its page, it prints the following error:
```
    File "/app/server/server.py", line 19, in <module>
    from . import assets, constants, package_search, storage
    File "/app/server/storage.py", line 206, in <module>
    download_searchable_packages())
    File "/app/server/storage.py", line 188, in download_searchable_packages
    'package-artifacts/searchable.json').get()['Body']
    File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
    File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
    File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
    File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
    botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
```

**Comment by wende** [comment]
I can't seem to replicate that. Maybe an S3 bucket was inaccessible for some time?

**Comment by azazel75** [comment]
I stil get it, both on FF and Chromium.

**Comment by azazel75** [comment]
Don't you get an error in the logs?

**Comment by wende** [comment]
Alright I'll look into that

**Comment by mikecann** [comment]
Still doesnt work for me...

```
botocore.errorfactory.NoSuchBucket
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist

Traceback (most recent call last)
File "/app/server/server.py", line 19, in <module>
from . import assets, constants, package_search, storage
File "/app/server/storage.py", line 206, in <module>
download_searchable_packages())
File "/app/server/storage.py", line 188, in download_searchable_packages
'package-artifacts/searchable.json').get()['Body']
File "/usr/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
response = action(self, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
response = getattr(parent.meta.client, operation_name)(**params)
File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 557, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PAN
```

BTW noticed this project hasnt been updated in a while, is it abandonware now?

**Comment by wende** [comment]
@mikecann Not abandoned. But currently I'm the only maintainer and have an unfortunately low amount of spare time to dedicate to that project.

I'm delivering about ±10 hours weekly for Elchemy, all of which goes to the development of the own type inference algorithm.


Regarding this very issue - turns out it's not the Elchemy-live that isn't working - it's the link on the main website that points to the old domain. That's why I wasn't able to replicate that. It took me a while to find out what's going on.
All that needs to change is the link to http://elchemy.neontree.pl/new

**Comment by mikecann** [comment]
Ahh right okay, thanks mate :)
